### ISSUE TITLE
Rename `themes-used` to `list-themes`

### ISSUE THREAD

**Issue by david-poindexter** [UpendoVentures/Upendo-Dnn-Prompt#16]
## Is your feature request related to a problem?
I recommend following the naming convention for `Prompt` commands,

## Describe the solution you'd like
Consider naming the `themes-used` command as `list-themes` to conform with `Prompt` command naming convention.

## Describe alternatives you've considered
n/a

## Additional context
It would be awesome to see this command in DNN Platform.  😉

**Comment by WillStrohl** [comment]
Same, same, same!  :D  Thanks, David!

**Comment by david-poindexter** [comment]
<img src="https://media4.giphy.com/media/XAdbHJywVjF5K/giphy.gif"/>
