### ISSUE TITLE
Rename `popup-mode` to `set-popups`

### ISSUE THREAD

**Issue by david-poindexter** [UpendoVentures/Upendo-Dnn-Prompt#17]
## Is your feature request related to a problem?
I recommend following the naming convention for `Prompt` commands,

## Describe the solution you'd like
Consider naming the `popup-mode` command as `set-popups` to conform with `Prompt` command naming convention.

## Describe alternatives you've considered
n/a

## Additional context
It would be awesome to see this command in DNN Platform.  😉

**Comment by WillStrohl** [comment]
Same response and feedback as your previous issue.  Great stuff!  :)

**Comment by david-poindexter** [comment]
Same awesomeness as your previous response to my previous issue!  😆👍🏼

**Comment by WillStrohl** [comment]
Should I start adding taco gifs now?  😆

**Comment by david-poindexter** [comment]
<img src="https://media0.giphy.com/media/3o6ZtkmiFtpBvii6uQ/giphy.gif"/>
