### ISSUE TITLE
Rename `debug-mode` to `set-debug`

### ISSUE THREAD

**Issue by david-poindexter** [UpendoVentures/Upendo-Dnn-Prompt#18]
## Is your feature request related to a problem?
I recommend following the naming convention for `Prompt` commands,

## Describe the solution you'd like
Consider naming the `debug-mode` command as `set-debug` to conform with `Prompt` command naming convention.

## Describe alternatives you've considered
n/a

## Additional context
It would be awesome to see this command in DNN Platform.  😉

**Comment by WillStrohl** [comment]
Great feedback!  

Part of the reason for updates coming here first was not only to illustrate things for DNN Summit attendees, but also to get feedback and maturity on the commands I've added and will add in the future, before doing a PR into the DNN core.

**Comment by david-poindexter** [comment]
Awesomeness!
