### ISSUE TITLE
SI: Command set-demousers Not Working if Membership Rules are Are Not Met

### ISSUE THREAD

**Issue by jeremy-farrance** [UpendoVentures/Upendo-Dnn-Prompt#47]
## Sponsorship  

- [x] I'm already a sponsor... Woot!  

## Describe the bug  
This is actually a two-for-one in that I think there are two separate issues.
 
When the AspNetSqlMembershipProvider settings are tougher than the defaults (e.g. minRequiredPasswordLength is 7 by default and you've set it to 10):

A. `set-demousers` claims to be Successful, does not actually create any users
B.  and also there are no errors in the Admin Logs (usually these commands are very verbose about what they did)

## Software Versions  
- DNN:  09.12.00
- Module:  01.06.00  

## To Reproduce  
1. Edit your web.config so that `minRequiredPasswordLength="17"` 
2. Reload a page, then go to PersonaBar, Settings / Security, Member Accounts tab, Registration Settings subtab, and scroll down and verify that "Min Password Length" is now showing 17 
3. Go to Prompt and execute the `set-demousers` command (notice it is now faster than normal?) and it should claim success
4. Restart Application or Clear Cache if you like to do such things
5. (A) Go to Users and none of the demo ones (e.g. Tony Stark) have been added
6. (B) Go to Admin Logs and a) there are no errors logged and b) there are none of the many normal entries of Type = New User (though there is the one Type=Prompt Alert saying, "Command set-demousers IsValid True TypeFullName Upendo.Modules.UpendoPromp")

## Expected behavior  
A batch of demo users should have been added and details about what was done added to the Admin Logs

## Actual behavior  
No users created and no errors were logged

## Screenshots  
![image](https://github.com/UpendoVentures/Upendo-Dnn-Prompt/assets/653301/e9229765-dcd2-4f87-8944-0a5228091789)

![image](https://github.com/UpendoVentures/Upendo-Dnn-Prompt/assets/653301/0097c437-1b48-49c1-ba5d-13e9fa991d33)

**Comment by WillStrohl** [comment]
@jeremy-farrance  Excellent catch, and also, thank you for [being a sponsor](https://github.com/sponsors/UpendoVentures)!

**Comment by WillStrohl** [comment]
@jeremy-farrance In thinking about this, I guess the best way to deal with this is to add a password flag/option for someone to enter their own.  What do you think?

**Comment by jeremy-farrance** [comment]
It gets complex quickly. My first thought was to read the DNN settings from web.config and build the user list dynamically. But there still could be errors. So maybe the first thing it to just get it catching and reporting the error in a way that is useful to the user. And then work through whether or not to add arguments the user could supply, or "prompt" the user for a password complex enough or ... I think there might be a simpler approach, I am just not seeing it yet.

Another option might be to just add the user data so its already complex enough to work no matter what the Membership settings are. Generate a 40 character password with 17 non-alpha characters or some such. :)

**Comment by WillStrohl** [comment]
Well, the other complexity is that the person using this feature may need to type in the password over and over.  

In thinking about who the demo user command is intended, I'm not sure that the purpose of this command is great for an existing site with higher constraints like that.  Do your development environments have this increased security set-up?

**Comment by jeremy-farrance** [comment]
I agree, the two main use-cases I have are the only ones I can think of atm. 

- doing demos for clients or tutorial recordings
- testing during development

And you are right, in both cases, it does seem unlikely that you'd be running in a production environment. So I guess the best first step forward is to just catch and report the error with enough detail so that the user understands what just happened and can make their own decision about how and whether or not to fix it.

**Comment by WillStrohl** [comment]
> ...
> 
> I guess the best first step forward is to just catch and report the error with enough detail so that the user understands what just happened and can make their own decision about how and whether or not to fix it.

@jeremy-farrance We're going to add this update.
